<?php
//  ------------------------------------------------------------------------ //
//                    Discography Dabase Module for                          //
//               XOOPS - PHP Content Management System 2.0                   //
//                   Copyright (c) 2008 Dana Harris                          //
//                       http://www.optikool.com                             //
// ------------------------------------------------------------------------- //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //

$modversion['name'] = _CDBASE_NAME;
$modversion['version'] = "1.32";
$modversion['description'] = _CDBASE_DESC;
$modversion['credits'] = "Modified code from the FAQ module of XOOPS 2.0(RC2)";
$modversion['author'] = "Dana Harris http://www.optikool.com/";
$modversion['help'] = "cdbase.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "images/slogo.png";
$modversion['dirname'] = "cdbase";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "cdbase_artists";
$modversion['tables'][1] = "cdbase_discs";
$modversion['tables'][2] = "cdbase_lyrics";
$modversion['tables'][3] = "cdbase_gens";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Main contents
$modversion['hasMain'] = 1;

// Blocks
$modversion['blocks'][1]['file'] = "last_disc.php";
$modversion['blocks'][1]['name'] = _CDBASE_BNAME;
$modversion['blocks'][1]['description'] = _CDBASE_BDESC;
$modversion['blocks'][1]['show_func'] = "last_disc_show";
$modversion['blocks'][1]['template'] = 'last_disc_block.html';

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "cdbase_search";

// Templates
$modversion['templates'][1]['file'] = 'cdbase_index.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'cdbase_artist.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'cdbase_lyric.html';
$modversion['templates'][3]['description'] = '';
$modversion['templates'][4]['file'] = 'cdbase_album.html';
$modversion['templates'][4]['description'] = '';

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['pageName'] = 'index.php';
$modversion['comments']['itemName'] = 'id_art';

// Config Settings

// name of config option for accessing its specified value. i.e. $xoopsModuleConfig['storyhome']
$modversion['config'][1]['name'] = 'intro';
// title of this config option displayed in config settings form
$modversion['config'][1]['title'] = '_CDBASE_INTRO';
// description of this config option displayed under title
$modversion['config'][1]['description'] = '_CDBASE_INTRO_DESC';
// form element type used in config form for this option. can be one of either textbox, textarea, select, select_multi, yesno, group, group_multi
$modversion['config'][1]['formtype'] = 'textarea';
// value type of this config option. can be one of either int, text, float, array, or other
// form type of 'group_multi', 'select_multi' must always be 'array'
// form type of 'yesno', 'group' must be always be 'int'
$modversion['config'][1]['valuetype'] = 'text';
// the default value for this option
// ignore it if no default
// 'yesno' formtype must be either 0(no) or 1(yes)
//$modversion['config'][1]['default'] = 100;
// options to be displayed in selection box
// required and valid for 'select' or 'select_multi' formtype option only
// language constants can be used for both array keys and values
//$modversion['config'][1]['options'] = array('5' => 5, '10' => 10, '50' => 50, '100' => 100, '200' => 200, '500' => 500, '1000' => 1000);


// Notification
$modversion['hasNotification'] = 1;
$modversion['notification']['lookup_file'] = 'include/notification.inc.php';
$modversion['notification']['lookup_func'] = 'item_info';

$modversion['notification']['category'][1]['name'] = 'disc';
$modversion['notification']['category'][1]['title'] = _CB_DISC_NOTIFY;
$modversion['notification']['category'][1]['description'] = _CB_DISC_NOTIFYDSC;
$modversion['notification']['category'][1]['subscribe_from'] = 'index.php';
$modversion['notification']['category'][1]['item_name'] = 'id_art';

$modversion['notification']['category'][2]['name'] = 'global';
$modversion['notification']['category'][2]['title'] = _CB_GLOBAL_NOTIFY;
$modversion['notification']['category'][2]['description'] = _CB_GLOBAL_NOTIFYDSC;
$modversion['notification']['category'][2]['subscribe_from'] = 'index.php';
$modversion['notification']['category'][2]['item_name'] = '';

$modversion['notification']['event'][1]['name'] = 'new_disc';
$modversion['notification']['event'][1]['category'] = 'disc';
$modversion['notification']['event'][1]['title'] = _CB_DISC_NEWPOST_NOTIFY;
$modversion['notification']['event'][1]['caption'] = _CB_DISC_NEWPOST_NOTIFYCAP;
$modversion['notification']['event'][1]['description'] = _CB_DISC_NEWPOST_NOTIFYDSC;
$modversion['notification']['event'][1]['mail_template'] = 'disc_new_notify';
$modversion['notification']['event'][1]['mail_subject'] = _CB_DISC_NEWPOST_NOTIFYSBJ;

$modversion['notification']['event'][2]['name'] = 'new_artist';
$modversion['notification']['event'][2]['category'] = 'global';
$modversion['notification']['event'][2]['title'] = _CB_GLOBAL_ARTIST_NEW_NOTIFY;
$modversion['notification']['event'][2]['caption'] = _CB_GLOBAL_ARTIST_NEW_NOTIFYCAP;
$modversion['notification']['event'][2]['description'] = _CB_GLOBAL_ARTIST_NEW_NOTIFYDSC;
$modversion['notification']['event'][2]['mail_template'] = 'global_artist_new_notify';
$modversion['notification']['event'][2]['mail_subject'] = _CB_GLOBAL_ARTIST_NEW_NOTIFYSBJ;

?>